=== rero/rero-ils/rero_ils/modules/patrons_types/jsonschemas/patrons_types/patron_type-v0.0.1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "PatronType",
  "description": "JSON schema for patrons_types.",
  "additionalProperties": false,
  "required": [
    "$schema",
    "pid",
    "name",
    "description",
    "organisation_pid"
  ],
  "properties": {
    "$schema": {
      "title": "Schema",
      "description": "Schema to validate patrons_types records against.",
      "type": "string",
      "minLength": 9
    },
    "pid": {
      "title": "Patron type ID",
      "type": "string",
      "minLength": 1
    },
    "name": {
      "title": "Patron type name",
      "description": "a short name of the Patron type",
      "type": "string",
      "minLength": 2
    },
    "description": {
      "title": "Patron type description",
      "description": "The description of the Patron type",
      "type": "string"
    },
    "organisation_pid": {
      "title": "Organisation ID",
      "type": "string"
    }
  }
}

=== rero/rero-ils/data/items_types.json
[
  {
    "$schema": "https://ils.test.rero.ch/schema/items_types/item_type-v0.0.1.json",
    "pid": "1",
    "name": "standard",
    "description": "standard checkout",
    "organisation_pid": "1"
  },
  {
    "$schema": "https://ils.test.rero.ch/schema/items_types/item_type-v0.0.1.json",
    "pid": "2",
    "name": "short",
    "description": "short checkout",
    "organisation_pid": "1"
  },
  {
    "$schema": "https://ils.test.rero.ch/schema/items_types/item_type-v0.0.1.json",
    "pid": "3",
    "name": "on-site",
    "description": "on-site checkout",
    "organisation_pid": "1"
  },
  {
    "$schema": "https://ils.test.rero.ch/schema/items_types/item_type-v0.0.1.json",
    "pid": "4",
    "name": "no-checkout",
    "description": "no checkout",
    "organisation_pid": "1"
  }
]
