=== rero/rero-ils/rero_ils/modules/locations/jsonschemas/locations/location-v0.0.1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Location",
  "description": "JSON schema for an location",
  "additionalProperties": false,
  "required": [
    "$schema",
    "pid",
    "code",
    "name",
    "library"
  ],
  "properties": {
    "$schema": {
      "title": "Schema",
      "description": "Schema to validate organisation records against.",
      "type": "string",
      "minLength": 9,
      "default": "https://ils.rero.ch/schema/locations/location-v0.0.1.json"
    },
    "pid": {
      "title": "Location ID",
      "type": "string"
    },
    "code": {
      "title": "Code",
      "description": "Code of the location.",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "description": "Name of the location.",
      "type": "string",
      "minLength": 1
    },
    "is_pickup": {
      "title": "Is pickup location",
      "type": "boolean",
      "default": false,
      "description": "Qualify this location as a pickup location."
    },
    "is_online": {
      "title": "Is online location",
      "type": "boolean",
      "default": false,
      "description": "Qualify this location as an online location."
    },
    "pickup_name": {
      "title": "Pickup location name",
      "type": "string",
      "description": "Displayed pickup location name, if different from the location name."
    },
    "library": {
      "title": "Library",
      "type": "object",
      "properties": {
        "$ref": {
          "title": "Library URI",
          "type": "string",
          "pattern": "^https://ils.rero.ch/api/libraries/.*?$"
        }
      }
    }
  }
}

=== rero/rero-ils/data/locations.json
[
  {
    "pid": "1",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-CANT1-PUB",
    "name": "Espaces publics",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/1"
    },
    "is_pickup": true,
    "pickup_name": "AOSTE CANT1: Espaces publics"
  },
  {
    "pid": "2",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-CANT1-BIBLIOGR",
    "name": "Bibliographie vald\u00f4taine",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/1"
    }
  },
  {
    "pid": "3",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-CANT1-MAGA",
    "name": "Magasin A",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/1"
    }
  },
  {
    "pid": "4",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-CANT1-ONL",
    "name": "Online",
    "is_pickup": false,
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/1"
    },
    "is_online": true
  },
  {
    "pid": "5",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-CANT2-PUB",
    "name": "Espaces publics",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/2"
    },
    "is_pickup": true,
    "pickup_name": "AOSTE CANT2: Espaces publics"
  },
  {
    "pid": "7",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-AVISE-FIC",
    "name": "Section fiction",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/3"
    }
  },
  {
    "pid": "8",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-AVISE-DOC",
    "name": "Section documentaires",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/3"
    }
  },
  {
    "pid": "9",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-AVISE-ENF",
    "name": "Section enfants",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/3"
    }
  },
  {
    "pid": "10",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-AVISE-MUL",
    "name": "Section multim\u00e9dia",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/3"
    }
  },
  {
    "pid": "11",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-AVISE-PUB",
    "name": "Espaces publics",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/3"
    },
    "is_pickup": true,
    "pickup_name": "AOSTE-AVISE-PUB: Espaces publics"
  },
  {
    "pid": "12",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-AVISE-ONL",
    "name": "Online",
    "is_pickup": false,
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/3"
    },
    "is_online": true
  },
  {
    "pid": "13",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-LYCEE-PUB",
    "name": "Espaces publics",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/4"
    },
    "is_pickup": true,
    "pickup_name": "AOSTE-LYCEE: Espaces publics"
  },
  {
    "pid": "14",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "AOSTE-LYCEE-MAT",
    "name": "Travaux de maturit\u00e9",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/4"
    }
  },
  {
    "pid": "16",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "HOG-RESTR",
    "name": "Restricted Section",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/5"
    }
  },
  {
    "pid": "17",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "HOG-PUBL",
    "name": "Public Section",
    "is_pickup": true,
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/5"
    }
  },
  {
    "pid": "18",
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "code": "HOG-ONL",
    "name": "Online",
    "is_pickup": false,
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/5"
    },
    "is_online": true
  },
  {
    "$schema": "https://ils.rero.ch/schema/locations/location-v0.0.1.json",
    "pid": "19",
    "code": "REZ",
    "name": "Rez-de-chauss\u00e9e",
    "library": {
      "$ref": "https://ils.rero.ch/api/libraries/6"
    },
    "is_pickup": true,
    "pickup_name": "Biblioth\u00e8que cantonale"
  }
]
